__author__ = "ZiXing"

datas = [{"lv1_name": "广东省",
          "lv1_datas":[{"lv2_name": "深圳市",
                        "lv2_datas":[{"lv3_name": "龙华新区", "lv1_datas":[]},
                                     {"lv3_name": "福田区", "lv1_datas": []},
                                     {"lv3_name": "龙岗区", "lv1_datas": []},
                                     {"lv3_name": "其他区", "lv1_datas": []}]},
                       {"lv2_name": "广州市",
                        "lv2_datas": [{"lv3_name": "天河区", "lv1_datas": []},
                                      {"lv3_name": "海珠区", "lv1_datas": []},
                                      {"lv3_name": "荔湾区", "lv1_datas": []},
                                      {"lv3_name": "越秀区", "lv1_datas": []}]},
                       {"lv2_name": "珠海市",
                        "lv2_datas": [{"lv3_name": "斗门区", "lv1_datas": []},
                                      {"lv3_name": "金湾区", "lv1_datas": []},
                                      {"lv3_name": "香洲区", "lv1_datas": []}]}
                       ]},
        {"lv1_name": "陕西省",
                  "lv1_datas":[{"lv2_name": "西安市",
                                "lv2_datas":[{"lv3_name": "龙华新区", "lv1_datas":[]},
                                             {"lv3_name": "福田区", "lv1_datas": []},
                                             {"lv3_name": "龙岗区", "lv1_datas": []},
                                             {"lv3_name": "其他区", "lv1_datas": []}]},
                               {"lv2_name": "渭南市",
                                "lv2_datas": [{"lv3_name": "天河区", "lv1_datas": []},
                                              {"lv3_name": "海珠区", "lv1_datas": []},
                                              {"lv3_name": "荔湾区", "lv1_datas": []},
                                              {"lv3_name": "越秀区", "lv1_datas": []}]},
                               {"lv2_name": "宝鸡市",
                                "lv2_datas": [{"lv3_name": "斗门区", "lv1_datas": []},
                                              {"lv3_name": "金湾区", "lv1_datas": []},
                                              {"lv3_name": "香洲区", "lv1_datas": []}]}
                               ]},
        {"lv1_name": "湖北省",
                  "lv1_datas":[{"lv2_name": "武汉市",
                                "lv2_datas":[{"lv3_name": "龙华新区", "lv1_datas":[]},
                                             {"lv3_name": "福田区", "lv1_datas": []},
                                             {"lv3_name": "龙岗区", "lv1_datas": []},
                                             {"lv3_name": "其他区", "lv1_datas": []}]},
                               {"lv2_name": "荆门市",
                                "lv2_datas": [{"lv3_name": "天河区", "lv1_datas": []},
                                              {"lv3_name": "海珠区", "lv1_datas": []},
                                              {"lv3_name": "荔湾区", "lv1_datas": []},
                                              {"lv3_name": "越秀区", "lv1_datas": []}]},
                               {"lv2_name": "黄冈市",
                                "lv2_datas": [{"lv3_name": "斗门区", "lv1_datas": []},
                                              {"lv3_name": "金湾区", "lv1_datas": []},
                                              {"lv3_name": "香洲区", "lv1_datas": []}]}
                               ]},
        {"lv1_name": "宁夏省",
                  "lv1_datas":[{"lv2_name": "银川市",
                                "lv2_datas":[{"lv3_name": "龙华新区", "lv1_datas":[]},
                                             {"lv3_name": "福田区", "lv1_datas": []},
                                             {"lv3_name": "龙岗区", "lv1_datas": []},
                                             {"lv3_name": "其他区", "lv1_datas": []}]},
                               {"lv2_name": "吴中市",
                                "lv2_datas": [{"lv3_name": "天河区", "lv1_datas": []},
                                              {"lv3_name": "海珠区", "lv1_datas": []},
                                              {"lv3_name": "荔湾区", "lv1_datas": []},
                                              {"lv3_name": "越秀区", "lv1_datas": []}]}
                               ]}
         ]

print (datas)